### ISSUE TITLE
Should use API key rather than username and password

### ISSUE THREAD

**Issue by cunneen** [RicardormDev/ClockifyPlugin#2]
[Clockify docs](https://clockify.me/developers-api) recommend using the API Key rather than username and password. 

This is a much better approach as it avoids the pitfalls of password reuse (for users who have poor password security, which sadly is a lot of users).

<img width="907" alt="Screen Shot 2021-05-24 at 9 16 08 am" src="https://user-images.githubusercontent.com/1751645/119284478-631bec00-bc72-11eb-83a9-97e886ff49a7.png">

**Comment by DevSlashRichie** [comment]
Hey!
When the plugin was created the public API lacked some functions that are available on this plugin. I decided to use the "private" API. The only way I found to generate a token for it was using login credentials. 

If this key is also available for private API, or if the endpoints are now available at the public API, you can either comment that here or make a pull request. 

Thanks for your observation.
